resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      products:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeout-duration: 4s
    instances:
      products:
        baseConfig: default
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
      client:
        registration:
          client-app:
            provider: spring
            client-id: gateway
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:9090/authorized
            scope:
              - openid
              - profile
            client-name: client-app
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000
  cloud:
    gateway:
      routes:
        - id: authentication
          uri: lb://authentication
          predicates:
            - Path=/gateway/authentication/**
          filters:
            - StripPrefix=2
        - id: users
          uri: lb://users
          predicates:
            - Path=/gateway/users/**
          filters:
            - StripPrefix=2
        - id: products
          uri: lb://products
          predicates:
            - Path=/gateway/products/**
            # - Header=token-example, 12345
            # - Method=GET
            # - Query=name, products-example
            # - Cookie=cookie, abdef
          filters:
            - name: CircuitBreaker
              args:
                name: products
                statusClosed: 500
            - StripPrefix=2
            - name: SampleCookie
              args:
                name: cookieName
                value: sebastian
                message: Hola, este es mi mensaje personalizado para productos
        - id: items
          uri: lb://items
          predicates:
            - Path=/gateway/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=request-obligatory-example, abc
            - AddResponseHeader=response-obligatory-example, 321
            - AddRequestParameter=name, sebastian