spring:
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://products
          predicates:
            - Path=/gateway/products/**
          filters:
            - StripPrefix=2
        - id: items
          uri: lb://items
          predicates:
            - Path=/gateway/items/**
          filters:
            - StripPrefix=2