spring:
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://products
          predicates:
            - Path=/gateway/products/**
            # - Header=token-example, 12345
            # - Method=GET
            # - Query=name, products-example
            # - Cookie=cookie, abdef
          filters:
            - StripPrefix=2
            - name: SampleCookie
              args:
                name: cookieName
                value: sebastian
                message: Hola, este es mi mensaje personalizado para productos
        - id: items
          uri: lb://items
          predicates:
            - Path=/gateway/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=request-obligatory-example, abc
            - AddResponseHeader=response-obligatory-example, 321
            - AddRequestParameter=name, sebastian