spring:
  application:
    name: users
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/microservices_products_db
    username: root
    password: 12345
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
server:
  port: 9093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/